### ISSUE TITLE
Release Feluda 1.0 

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/feluda#401]
### Overview 
We have to make Feluda easy to use for other social media researchers and content consumers. This means making feluda available as a ready to use python library by publishing it to registries like pypi, creating documentation for common use cases of feluda, Finalizing public API of the library etc.

Since 1.0 release also opens possibilities to onboard new contributors, we will also clean up the setup documentation, improve the test suite and benchmarking suite and document it.

### Features, Tickets, User Stories
- [ ] Finalize Public API
- [ ] Improve Test Coverage
- [ ] Standardize Benchmarking 
- [ ] Create Recipes for common use case
